# Generated by CPYCMS on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
