# Generated by CPYCMS on 2026-06-23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_articlecomment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('article', 'Article'), ('work', 'Work')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=80)),
                ('os_name', models.CharField(blank=True, default='', max_length=80)),
                ('device_type', models.CharField(blank=True, default='', max_length=40)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'content_likes',
                'indexes': [
                    models.Index(fields=['target_type', 'target_id'], name='idx_likes_target'),
                    models.Index(fields=['fingerprint_hash', 'created_at'], name='idx_likes_fp_created'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('target_type', 'target_id', 'fingerprint_hash'), name='uq_like_target_fp'),
                ],
            },
        ),
    ]
