# Generated by Django 5.2.4 on 2026-06-24 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_article_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['view_count'], name='idx_article_view_count'),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['article', 'is_approved', 'created_at'], name='idx_comment_art_appr_crt'),
        ),
        migrations.AddIndex(
            model_name='contentlike',
            index=models.Index(fields=['ip_address', 'created_at'], name='idx_likes_ip_created'),
        ),
    ]
