# Generated by CPYCMS on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_article_idx_article_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='author_role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('admin', 'Admin')], default='visitor', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='author_role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('admin', 'Admin')], default='visitor', max_length=20),
        ),
    ]
